import { IGasto } from "../interfaces/IGastos";

class MovimentacoesRepository {
  buscarMovimentacoes() {
    const gastos: IGasto[] = [
      {
        id: 1,
        valor: 100,
        data: new Date(),
        tipo: 1,
        descricao: "Uber",
        idCategoria: 1,
        idCartao: 2,
        idPessoa: 1,
      },
      {
        id: 2,
        valor: 300,
        data: new Date(),
        tipo: 1,
        descricao: "Hamburguer",
        idCategoria: 2,
        idCartao: 3,
        idPessoa: 2,
      },
      {
        id: 3,
        valor: 400,
        data: new Date(),
        tipo: 0,
        descricao: "Caixa Larissa",
        idCategoria: 3,
        idCartao: 4,
        idPessoa: 3,
      },
      {
        id: 4,
        valor: 1900,
        data: new Date(),
        tipo: 1,
        descricao: "Serviços Mão de obraaaaaaaaaaa",
        idCategoria: 3,
        idPessoa: 1,
      },
      {
        id: 5,
        valor: 1900,
        data: new Date(),
        tipo: 0,
        descricao: "Larissa",
        idCategoria: 3,
        idPessoa: 1,
      },
      {
        id: 6,
        valor: 100,
        data: new Date(),
        tipo: 1,
        descricao: "Uber",
        idCategoria: 1,
        idCartao: 2,
        idPessoa: 1,
      },
      {
        id: 7,
        valor: 100,
        data: new Date(),
        tipo: 1,
        descricao: "Uber",
        idCategoria: 1,
        idCartao: 2,
        idPessoa: 1,
      },
      {
        id: 8,
        valor: 100,
        data: new Date(),
        tipo: 1,
        descricao: "Uber",
        idCategoria: 1,
        idCartao: 2,
        idPessoa: 1,
      },
      {
        id: 9,
        valor: 100,
        data: new Date(),
        tipo: 1,
        descricao: "Uber",
        idCategoria: 1,
        idCartao: 2,
        idPessoa: 1,
      },
      {
        id: 10,
        valor: 100,
        data: new Date(),
        tipo: 1,
        descricao: "Uber",
        idCategoria: 1,
        idCartao: 2,
        idPessoa: 1,
      },
      {
        id: 11,
        valor: 100,
        data: new Date(),
        tipo: 1,
        descricao: "Uber",
        idCategoria: 1,
        idCartao: 2,
        idPessoa: 1,
      },
      {
        id: 12,
        valor: 100,
        data: new Date(),
        tipo: 1,
        descricao: "Uber",
        idCategoria: 1,
        idCartao: 2,
        idPessoa: 1,
      },
      {
        id: 13,
        valor: 100,
        data: new Date(),
        tipo: 1,
        descricao: "Uber",
        idCategoria: 1,
        idCartao: 2,
        idPessoa: 1,
      },
      {
        id: 14,
        valor: 100,
        data: new Date(),
        tipo: 1,
        descricao: "Uber",
        idCategoria: 1,
        idCartao: 2,
        idPessoa: 1,
      },
    ];

    return gastos;
  }
}

export default new MovimentacoesRepository();
